[env:kitchen]
platform = espressif8266
board = d1_mini
framework = arduino
upload_protocol = espota
upload_port = 192.168.0.209
build_flags = 
    -DDEVICE_HOST=\"EVCC-DisplayLarge\"
    -DMQTT_USER=\"displaylarge\"
    -DMQTT_PASS=\"displaylarge\"
lib_deps = 
    sstaub/Ticker@^4.4.0
    adafruit/Adafruit GFX Library@^1.11.3
    adafruit/Adafruit SSD1306@^2.5.7
    khoih-prog/ESP_WifiManager@^1.11.0
    adafruit/Adafruit ST7735 and ST7789 Library@^1.9.3
    bblanchon/ArduinoJson@^6.20.0
    knolleary/PubSubClient@^2.8

[env:test]
platform = espressif8266
board = d1_mini
framework = arduino
upload_protocol = espota
upload_port = 192.168.0.204
build_flags = 
    -DDEVICE_HOST=\"EVCC-DisplayLargeTest\"
    -DMQTT_USER=\"displaylargetest\"
    -DMQTT_PASS=\"displaylargetest\"
lib_deps = 
    sstaub/Ticker@^4.4.0
    adafruit/Adafruit GFX Library@^1.11.3
    adafruit/Adafruit SSD1306@^2.5.7
    khoih-prog/ESP_WifiManager@^1.11.0
    adafruit/Adafruit ST7735 and ST7789 Library@^1.9.3
    bblanchon/ArduinoJson@^6.20.0
    knolleary/PubSubClient@^2.8